### ISSUE TITLE
[Question] 和hexo-all-minifier有什么不同么？

### ISSUE THREAD

**Issue by NoahDragon** [Rozbo/hexo-neat#1]
我看Hexo plugin里面hexo-all-minifier和这个功能基本一致，有什么特殊的不同么？

**Comment by ohroy** [comment]
这个插件的确是受`hexo-all-minifier`的启发而弄的，但初衷并非是山寨。我最初用`hexo-all-minifier`的时候他由于`image-minifier`的bug无法正常使用，而且由于`hexo`的bug无法处理`html`，所以我在调试的过程中又自己弄了个。
而且这个插件的侧重与它不同之处在于我想实现**自动合并**js和css的功能，所以取名叫neat，但是一时之间我还没时间来完善这个。
所以功能和修复过的`hexo-all-minifier`几乎一致。

**Comment by NoahDragon** [comment]
👍

**Comment by Aloento** [comment]
自动合并js和css的功能有了吗
