### ISSUE TITLE
压缩不正常

### ISSUE THREAD

**Issue by wangfys** [Rozbo/hexo-neat#3]
我使用的主题是NexT
在hexo generate的过程中会出现Asset render failed: lib/canvas-ribbon/canvas-ribbon.js
然后打开的效果是隐藏大量篇幅变成Read More按钮这一功能没了,我猜是markdown转html的时候出的问题
把对js和css的压缩功能关闭,Asset render failed就不再发生了,但是read more还是没有显示...

**Comment by ohroy** [comment]
1. `Asset render failed` 字面上理解是渲染失败...然而这并不是由压缩直接导致的，因为压缩是发生在渲染之后。我猜是插件依赖冲突导致的？这里我没法复现。
2. `markdown`转html的过程中本插件没有参与，建议升级下相关依赖试试。
