### ISSUE TITLE
是否可以添加压缩程度的选项

### ISSUE THREAD

**Issue by ghost** [Rozbo/hexo-neat#5]
在压缩html时希望只删除行尾空格和空行，而不是把所有换行都删除。同时删除开头自动添加的生成时间。

**Comment by ohroy** [comment]
1. 压缩程度是有选项的，在readme里面有提到，其实就是参考[html-minifier](https://github.com/kangax/html-minifier)的参数，直接写到`neat_html`下面就可以了。
2. 开头添加的生成时间是为了实现统计与显示而设计的，暂没有移除计划。有时间的话会考虑加个选项控制吧。
